const fs = require('fs');
const path = require('path');

module.exports = function () {
	const versionTmpl = `// WARNING!!!
// THIS FILE WAS GENERATED BY THE PREBUILD SCRIPT!
// NO _NOT_ EDIT MANUALLY!

module.exports = '${require('../package').version}';
`;

	const versionFilename = path.resolve(__dirname, '..', 'lib', 'version.js');

	fs.writeFileSync(versionFilename, versionTmpl, 'utf8');
};
